name: Pull Request
on:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v21

      - name: Build site
        run: nix develop --command mkdocs build --site-dir public

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v1
        with:
          path: public
